# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  code:
    desc: Format and lint Python files with ruff
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .
