# https://taskfile.dev

version: "3"

includes:
  play:
    dir: ./playground
    taskfile: ./playground/Taskfile.yml

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  code:
    desc: Format and lint Python files with ruff
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .

  test:
    desc: Run Python tests with pytest
    cmds:
      - uv run pytest

  build:
    desc: Build the Python library wheel
    cmds:
      - uv build

  build-and-copy:
    desc: Build the Python library and copy wheel to playground/public/pyodide/
    cmds:
      - task: build
      - mkdir -p playground/public/pyodide
      - cp dist/*.whl playground/public/pyodide/
